    skinparam RectangleBackgroundColor white
    skinparam StorageBackgroundColor   white
    skinparam CardBackgroundColor      white
    skinparam CardBorderColor          white
    skinparam CardBorderThickness      0
    skinparam Shadowing                false
    skinparam DefaultTextAlignment     center
    skinparam Padding                  2
