@startuml

skinparam CardBackgroundColor white
skinparam CardBorderColor white
skinparam CardBorderThickness 0
skinparam Shadowing false


card "<img:../img/dudes/dinis-dude.png{scale=0.3}>"               as dinis
card "<img:../img/dudes/dude.png{scale=0.3}>"                     as dude
card "<img:../img/dudes/dude-holding-something.png{scale=0.3}>"   as holding
card "<img:../img/dudes/dude-not-sure.png{scale=0.3}>"            as not_sure
card "<img:../img/dudes/dude-on-the-move.png{scale=0.3}>"         as on_move
card "<img:../img/dudes/dude-scratching-head.png{scale=0.3}>"     as head




dinis   -> dude
dinis   -down-> holding
holding -down-> not_sure
holding -> on_move
dude    --> head

@enduml