'!include ../../diagrams/default-params.iuml

scale 800 width
skinparam Padding   2
skinparam card      {
                        fontSize 15
                    }
skinparam rectangle {
                        roundCorner 25
                    }

skinparam node      {
                        fontSize        40
                        backgroundColor #007BB7
                        fontColor       #white
                    }

!define card_brain      card Brain  as brain
!define card_pen        card Pen    as pen
!define card_book       card Book   as book
