@startuml

    !include_many ./STEM-tech-stack-common.iuml

    title
    <img:../../img/others/3rd-party/stem-logo.png{scale=0.2}>
              Tech Stack
    end title


'    newpage
'    !include_many ./STEM-tech-stack-common.iuml
'    rectangle " " as gen_x_box {
'
'        node "1975-1995"                    as gen_x
'        cloud "**Natural habitat of GenX** \n(Born between 1965–1976)"  as x_born
'
'        card_brain
'        card_pen
'        card_book
'
'
'        card "Scientific Calculator"    as x_calculator
'
'        gen_x       -l->    x_born #white
'        gen_x       -->     brain
'        brain       -->     pen
'        brain       -->     book
'        gen_x       -r->    x_calculator
'    }
'    newpage
'
'    !include_many ./STEM-tech-stack-common.iuml
'
'    rectangle " " as gen_y_box {
'
'        node "GEN Y"                    as gen_y
'        cloud "Born between 1977–1995"  as y_born
'
'        card Pen                        as y_pen
'        card Paper                      as y_paper
'        card Brain                      as y_brain
'        card Email                      as y_email
'        card Computer                   as y_computer
'        card Mobile                     as y_mobile
'        card Internet                   as y_internet
'        card Spreadsheets               as y_spreadsheets
'        card "Data Centers"             as y_data_centers
'
'
'        gen_y       -l->    y_born  #white
'        gen_y       -->     y_brain
'        y_brain     -->     y_pen
'        y_brain      -->    y_paper
'        y_computer  -->     y_email
'        y_mobile    -->     y_email
'        y_mobile    -->     y_internet
'        gen_y       -->     y_computer
'        gen_y       -->     y_mobile
'        y_computer  -->     y_internet
'        y_computer  -->     y_data_centers
'        gen_y       -r->    y_spreadsheets
'    }
'    newpage

    newpage

    !include_many ./STEM-tech-stack-common.iuml

    cloud "**Natural habitat of GenY** \n(Born between 1977–1995)" as date
    node "2005 - 2015" as GenZ

    GenZ -l->  date

    GenZ -d-> Manual
    GenZ -d-> Custom
    GenZ -d-> Product
    GenZ -d-> Invisible

    rectangle "Manual" {
        card brain
        card pen
        card books
        card ideas

        books -[#white]-> brain
        pen   -[#white]-> ideas
    }

    rectangle "Customized" as Custom {
        card "abc"
    }

    rectangle "Product or Service" as Product {
        card "abcd"
    }

    rectangle "Commodity or Invisible" as "Invisible" {
        card Maths
        card "Data Centers"
        card Internet
    }
    newpage

    !include_many ./STEM-tech-stack-common.iuml

    cloud "**Natural habitat of GenZ** \n(Born between 1996–2012)" as date
    node "2018 - 2023" as GenZ

    GenZ -l->  date

    GenZ -d-> Manual
    GenZ -d-> Custom
    GenZ -d-> Product
    GenZ -d-> Invisible

    rectangle "Manual" {
        card brain
        card pen
        card books
        card ideas

        books -[#white]-> brain
        pen   -[#white]-> ideas
    }

    rectangle "Customized" as Custom {
        card Scripting
        'card "Data Science"
        card "Bots"
        card Voice
    }

    rectangle "Product or Service" as Product {
        card "Apps"
        card "Serverless and cloud" as Serverless
        card "AI and ML"            as AI
        card "Slack"
        card "ELK"
        Apps       --> ELK
        Apps       --> Slack
        Serverless --> AI
    }

    rectangle "Commodity or Invisible" as "Invisible" {

        card "Computers"
        card "Mobile"
        card Email

        card "Spreadsheets"

        Email --> Spreadsheets
        Mobile --> Computers
    }

@enduml