@startuml


    !include ../diagrams/stem/STEM-tech-stack-common.iuml
    left to right direction



    rectangle " " as gen_x_box {

        node "GEN X"                    as gen_x
        cloud "Born between 1965–1976"  as x_born

        card Pen                        as x_pen
        card Paper                      as x_paper
        card Brain                      as x_brain
        card "Scientific Calculator"    as x_calculator

        gen_x      -l->    x_born #white
        gen_x      -->     x_brain
        x_brain    -->     x_pen
        x_brain    -->     x_paper
        gen_x      -r->    x_calculator

    }




    rectangle " " as gen_y_box {

        node "GEN Y"                    as gen_y
        cloud "Born between 1977–1995"  as y_born

        card Pen                        as y_pen
        card Paper                      as y_paper
        card Brain                      as y_brain
        card Email                      as y_email
        card Computer                   as y_computer
        card Mobile                     as y_mobile
        card Internet                   as y_internet
        card Spreadsheets               as y_spreadsheets
        card "Data Centers"             as y_data_centers


        gen_y       -l->    y_born  #white
        gen_y       -->     y_brain
        y_brain     -->     y_pen
        y_brain      -->    y_paper
        y_computer  -->     y_email
        y_mobile    -->     y_email
        y_mobile    -->     y_internet
        gen_y       -->     y_computer
        gen_y       -->     y_mobile
        y_computer  -->     y_internet
        y_computer  -->     y_data_centers
        gen_y       -r->    y_spreadsheets
    }


    rectangle " " as gen_z_box {
        node "GEN Z" as gen_z
        cloud "Born between 1996–TBD "  as z_born


        card Pen                        as z_pen
        card Paper                      as z_paper
        card Brain                      as z_brain
        card "Slack"                    as z_slack
        card "Bots"                     as z_bots
        card "AI and ML"                as z_ai_ml
        card "Apps"                     as z_apps
        card "Python"                   as z_python
        card "Hash DB and Graphs (ELK)"  as z_elk
        card "Cloud / Serverless"       as z_cloud

        gen_z       -l->    z_born   #white
        gen_z       -->     z_brain
        z_brain     -->     z_pen
        z_brain     -->     z_paper
        z_brain     -->     z_ai_ml
        gen_z       -->     z_apps
        z_apps      -->    z_slack
        z_apps      -->    z_bots
        gen_z       -r->    z_elk
        z_apps      -->     z_cloud
        gen_z       -->    z_python
        z_python   --> z_cloud

    }

'partition "abc 123" abc {
'
'    aa --> cc
'
'}
'
'--[hidden]-> middle
'
'partition "ddd" ddd {
'
'    aa1 --> bb1
'    aa1 --> cc1
'
'}
'
'middle -[hidden]----> aa1




@enduml